py.install_sources(
  '__init__.py',
  'acmos.py',
  'bodyslide.py',
  'bodyslide_linux.py',
  'cao.py',
  'creation_kit.py',
  'display_tweaks.py',
  'eet.py',
  'engine_fixes.py',
  'eslifier.py',
  'esm_fixes.py',
  'fnv4gb.py',
  'laa.py',
  'oblivion4gb.py',
  'fo3_version.py',
  'pandora.py',
  'registry.py',
  'skygen.py',
  'strings.py',
  'synthesis.py',
  'ttw.py',
  'xedit.py',
  'xtranslator.py',
  subdir: 'Utils/bethesda',
)
