subdir('games')

py.install_sources(
  'AmethystBanner.png',
  'archive-conflict-loser.png',
  'archive-conflict-mixed.png',
  'archive-conflict-redundant.png',
  'archive-conflict-winner.png',
  'arrow.png',
  'brush.png',
  'bundle_settings.png',
  'check_white.png',
  'close_black.png',
  'close_white.png',
  'collection.png',
  'conflict-loser.png',
  'conflict-mixed.png',
  'conflict-redundant.png',
  'conflict-winner.png',
  'cross.png',
  'deploy.png',
  'endorsed.png',
  'error.png',
  'eye1_black.png',
  'eye1_white.png',
  'eye2_black.png',
  'eye2_white.png',
  'faugus.png',
  'heroic.png',
  'info.png',
  'install.png',
  'left.png',
  'lock.png',
  'Logo.png',
  'Loot_info.png',
  'lutris.png',
  'minus.png',
  'nexus.png',
  'note.png',
  'notification.png',
  'plus.png',
  'profile.png',
  'proton.png',
  'protonBG.png',
  'radio_dot.png',
  'refresh.png',
  'rerun_fomod.png',
  'restore.png',
  'right.png',
  'root.png',
  'search.png',
  'settings.png',
  'steam.png',
  'tag.png',
  'tick.png',
  'title-bar.png',
  'tux.png',
  'ui.png',
  'Thunderstore.png',
  'update_modio.png',
  'update_thunderstore.png',
  'update.png',
  'UUID_Loser.png',
  'UUID_Partial.png',
  'UUID_Winner.png',
  'warning2.png',
  'warning.png',
  'wizard.png',
  subdir: 'icons',
)
