"""Reusable launch-time virtual filesystem support.

Game handlers opt in and supply their normal game/mod-data paths and deploy
metadata. The default backend binds a materialized profile-local shadow tree;
legacy native/FUSE overlay manifests remain supported for compatibility.
"""

from .overlay import (
    BACKEND_FUSE,
    BACKEND_KERNEL,
    BACKEND_SHADOW,
    MANIFEST_NAME,
    MANIFEST_VERSION,
    PENDING_NAME,
    RUNTIME_NAME,
    STATE_DIR_NAME,
    bubblewrap_status,
    build_layers,
    cleanup_deployment,
    deployment_state_profiles,
    effective_shadow_data_root,
    effective_shadow_root,
    effective_tool_data_root,
    effective_tool_game_root,
    finalize_deployment,
    fuse_overlay_status,
    has_any_deployment_state,
    has_deployment_state,
    manifest_path,
    pending_path,
    prefer_virtual_executable,
    sandbox_passthrough_command,
    state_dir,
    virtual_data_write_path,
    virtual_file,
    virtual_file_path,
    virtual_root_write_path,
    wrap_command,
)
from .game import ProfileVFSGameMixin

__all__ = (
    "BACKEND_FUSE",
    "BACKEND_KERNEL",
    "BACKEND_SHADOW",
    "MANIFEST_NAME",
    "MANIFEST_VERSION",
    "PENDING_NAME",
    "ProfileVFSGameMixin",
    "RUNTIME_NAME",
    "STATE_DIR_NAME",
    "bubblewrap_status",
    "build_layers",
    "cleanup_deployment",
    "deployment_state_profiles",
    "effective_shadow_data_root",
    "effective_shadow_root",
    "effective_tool_data_root",
    "effective_tool_game_root",
    "finalize_deployment",
    "fuse_overlay_status",
    "has_any_deployment_state",
    "has_deployment_state",
    "manifest_path",
    "pending_path",
    "prefer_virtual_executable",
    "sandbox_passthrough_command",
    "state_dir",
    "virtual_data_write_path",
    "virtual_file",
    "virtual_file_path",
    "virtual_root_write_path",
    "wrap_command",
)
