subdir('7 Days to Die')
subdir('Baldur\'s Gate 3')
subdir('BepInEx')
subdir('Bethesda')
subdir('Custom')
subdir('Cyberpunk 2077')
subdir('Daggerfall Unity')
subdir('Darktide')
subdir('Dragon Age Origins')
subdir('FromSoftware')
subdir('Jagged Alliance 3')
subdir('Kingdom Come Deliverance II')
subdir('Marvel Rivals')
subdir('Mewgenics')
subdir('Morrowind')
subdir('Mount & Blade II Bannerlord')
subdir('Oblivion Remastered')
subdir('RE_Engine_Invalidation')
subdir('RE_Engine_LooseLoading')
subdir('Red Dead Redemption 2')
subdir('Slay The Spire 2')
subdir('Stardew Valley')
subdir('The Sims 4')
subdir('The Witcher 3')

py.install_sources(
  '__init__.py',
  'base_game.py',
  'heroic_appnames.py',
  'ludusavi_saves.json',
  'ue5_game.py',
  subdir: 'Games',
)
