"""Bundled Ludusavi save-path data, looked up by Steam App ID or game title.

The data file (Games/ludusavi_saves.json) is generated by
tools/update_ludusavi_manifest.py from
https://github.com/mtkennerly/ludusavi-manifest -see that script for the
schema. Two copies can exist: the one bundled under ``src/Games/`` and one
downloaded from the Resources branch into the config folder (Utils.gh_sync),
so new games' save locations ship without an app update. Whichever carries the
later ``generated`` date wins -that way a fresh app release with newer data
beats a stale download, and vice versa.

Loading is lazy and thread-safe; nothing is read until the first lookup
(~70 ms for all ~12.6k games).
"""

from __future__ import annotations

import json
import re
import sys
import threading
from dataclasses import dataclass
from pathlib import Path

#: Data-file schema version this module understands. A file declaring anything
#: newer is ignored (a future app knows how to read it; this one does not).
SCHEMA_VERSION = 1

# Lives in Games/ rather than a data/ dir of its own: it is game data, and
# packaging (AppImage PKGBUILD, AUR) already copies Games/ wholesale.
_BUNDLED_PATH = Path(__file__).resolve().parent.parent / "Games" / "ludusavi_saves.json"

_lock = threading.Lock()
_games: "dict[str, dict] | None" = None
#: App ID → every title claiming it. One store page can ship two games (Quake
#: and Quake Enhanced are both app 2310), so this is a list, not a title.
_by_steam: dict[str, list[str]] = {}
_by_name: dict[str, str] = {}
_generated = ""

_NON_ALNUM = re.compile(r"[^a-z0-9]+")
# The generator writes "v" then "generated" first, so the header is readable
# without parsing the whole 2 MB file.
_HEADER_RE = re.compile(rb'"v"\s*:\s*(\d+).*?"generated"\s*:\s*"([0-9-]*)"', re.S)


@dataclass(frozen=True)
class ManifestEntry:
    """One game's save-path list from the Ludusavi manifest."""
    title: str
    steam_id: str
    # (token path, os constraint, store constraint); "" means unconstrained.
    paths: tuple[tuple[str, str, str], ...]


def normalize_title(name: str) -> str:
    """Fold a game title to a comparable key (lowercase, alphanumerics only)."""
    return _NON_ALNUM.sub("", (name or "").lower())


def peek_header(path: Path) -> "tuple[int, str] | None":
    """Read a data file's (schema version, generated date) without parsing it."""
    try:
        with open(path, "rb") as fh:
            head = fh.read(512)
    except OSError:
        return None
    match = _HEADER_RE.search(head)
    if match is None:
        return None
    try:
        return int(match.group(1)), match.group(2).decode("ascii", "replace")
    except ValueError:
        return None


def _best_data_file() -> "Path | None":
    """Pick the newest usable data file: downloaded copy vs bundled copy."""
    candidates = [_BUNDLED_PATH]
    try:
        from Utils.config_paths import get_ludusavi_manifest_path
        candidates.insert(0, get_ludusavi_manifest_path())
    except Exception:
        pass
    best: "tuple[str, Path] | None" = None
    for path in candidates:
        header = peek_header(path)
        if header is None or header[0] > SCHEMA_VERSION:
            continue
        # Same date → first candidate (the download) wins, so a re-published
        # file with fixes on the same day still takes effect.
        if best is None or header[1] > best[0]:
            best = (header[1], path)
    return best[1] if best else None


def _load() -> None:
    global _games, _generated
    if _games is not None:
        return
    with _lock:
        if _games is not None:
            return
        path = _best_data_file()
        if path is None:
            print("[ludusavi_manifest] no usable save-path data file",
                  file=sys.stderr, flush=True)
            _games = {}
            return
        try:
            blob = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"[ludusavi_manifest] load failed: {exc}", file=sys.stderr, flush=True)
            _games = {}
            return
        _games = blob.get("games") or {}
        _generated = blob.get("generated", "")
        for title, rec in _games.items():
            for sid in (rec.get("s", ""), *rec.get("x", ())):
                if sid:
                    _by_steam.setdefault(str(sid), []).append(title)
            _by_name.setdefault(normalize_title(title), title)


def reload() -> None:
    """Drop the cached data so the next lookup re-picks the newest file."""
    global _games, _generated
    with _lock:
        _games = None
        _generated = ""
        _by_steam.clear()
        _by_name.clear()


def lookup(steam_id: str = "", game_name: str = "") -> "ManifestEntry | None":
    """Find a game's save paths by Steam App ID, falling back to its title."""
    _load()
    if not _games:
        return None
    titles = list(_by_steam.get(str(steam_id or ""), ()))
    if not titles:
        by_name = _by_name.get(normalize_title(game_name))
        titles = [by_name] if by_name else []
    if not titles:
        return None
    # An app ID shared by several titles is a re-release sharing a store page
    # (Doom 1993 / Doom Enhanced, Quake / Quake Enhanced). Only one of them is
    # installed and every path is disk-verified, so merge their paths rather
    # than guess -picking the first title alphabetically resolved the ORIGINAL
    # game's saves for someone playing the enhanced one, and found nothing.
    folded = normalize_title(game_name)
    if folded and len(titles) > 1:
        titles.sort(key=lambda t: normalize_title(t) != folded)
    paths: list[tuple[str, str, str]] = []
    for title in titles:
        for path, os_name, store in _games[title].get("f", ()):
            triple = (path, os_name, store)
            if triple not in paths:
                paths.append(triple)
    return ManifestEntry(title=titles[0], steam_id=_games[titles[0]].get("s", ""),
                         paths=tuple(paths))


def data_info() -> tuple[int, str]:
    """Return (number of games known, generation date) for the active data."""
    _load()
    return len(_games or {}), _generated
