py.install_sources(
  'ReShade.ini',
  '__init__.py',
  '_mod_loader_installer_view.py',
  '_view_base.py',
  'bethesda_register_view.py',
  'bethini_view.py',
  'bg3_import_view.py',
  'bodyslide_linux_view.py',
  'bodyslide_view.py',
  'bsa_decompressor_view.py',
  'creationkit_view.py',
  'curated_profile_view.py',
  'dtkit_patch_view.py',
  'dyndolod_view.py',
  'engine_fixes_view.py',
  'eslifier_view.py',
  'esm_fixes_view.py',
  'fallout_downgrade_view.py',
  'fnv_4gb_view.py',
  'gpak_view.py',
  'modio_settings_view.py',
  'mscloader_view.py',
  'nif_viewer_view.py',
  'pandora_view.py',
  'pgpatcher_view.py',
  'plugin_audit_view.py',
  'proton_step.py',
  're_pak_restore_view.py',
  'reshade_view.py',
  'script_extender_view.py',
  'script_merger_view.py',
  'sdt_view.py',
  'skygen_view.py',
  'smapi_view.py',
  'srml_view.py',
  'synthesis_view.py',
  'texture_tool_view.py',
  'ttw_view.py',
  'wrye_bash_view.py',
  'xedit_view.py',
  subdir: 'wizards_qt',
)
